# Site settings
title: a x plus b
email: hello@axplusb.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about data, statistical learning and crowdfunding.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://axplusb.com" # the base hostname & protocol for your site
twitter_username: a_x_plus_b
#github_username:  jekyll

# Build settings
markdown: kramdown
